### ISSUE TITLE
Argument 1 must be an instance of xPDO\Om\xPDOQuery

### ISSUE THREAD

**Issue by wax100** [Sterc/calltoactiontv#13]
I get error on **98 line** in file **core/components/calltoactiontv/processors/resource/getlist.class.php**
Modx 2.7.2 dont like **\xPDO\Om\xPDOQuery**

`
Fatal error: Uncaught TypeError: Argument 1 passed to callToActionTVResourceGetListProcessor::prepareQueryBeforeCount() must be an instance of xPDO\Om\xPDOQuery, instance of xPDOQuery_mysql given, called in /paas/c0126/www/core/model/modx/modprocessor.class.php on line 560 and defined in /paas/c0126/www/core/components/calltoactiontv/processors/resource/getlist.class.php:98
Stack trace:
#0 /paas/c0126/www/core/model/modx/modprocessor.class.php(560): callToActionTVResourceGetListProcessor->prepareQueryBeforeCount(Object(xPDOQuery_mysql))
#1 /paas/c0126/www/core/components/calltoactiontv/processors/resource/getlist.class.php(136): modObjectGetListProcessor->getData()
#2 /paas/c0126/www/core/model/modx/modprocessor.class.php(495): callToActionTVResourceGetListProcessor->getData()
#3 /paas/c0126/www/core/components/calltoactiontv/processors/resource/getlist.class.php(91): modObjectGetListProcessor->process()
#4 /paas/c0126/www/core/model/modx/modprocessor.class.php(177): callToActionTVResourceGetListProcessor->process()
#5 /p in /paas/c0126/www/core/components/calltoactiontv/processors/resource/getlist.class.php on line 98`

**Comment by joeke** [comment]
Should be fixed with latest version https://modx.com/extras/package/calltoactiontv.
