### ISSUE TITLE
Context key is not supported in @SELECT bindings

### ISSUE THREAD

**Issue by Oetzie** [Sterc/calltoactiontv#16]
The context_key is always web because the ID of the resource is not send to the processBindings function.

In getlist processor the following rule must be changed:

`foreach (explode('||', $this->tvObject->processBindings($this->tvObject->get('elements'))) as $item) {`

To:

`foreach (explode('||', $this->tvObject->processBindings($this->tvObject->get('elements'), $this->getProperty('resourceId'))) as $item) {`

**Comment by sdrenth** [comment]
@Oetzie There's already a PR for this:
https://github.com/Sterc/calltoactiontv/pull/12

**Comment by joeke** [comment]
Should be fixed now in latest version.
