### ISSUE TITLE
URL's are not correct in some cases

### ISSUE THREAD

**Issue by joeke** [Sterc/calltoactiontv#3]
Been using calltoactiontv in a multicontext environment, but in a non-web context the url's are not prepended with the base_url.
context settings:
base_url: /werken-bij/
site_url: http://{http_host}/werken-bij/

Replacing the `$modx->makeUrl()` on line 29 in the calltoactiontv snippet with `$modx->makeUrl($cta['resource'], '', '', 'full');` fixes the issue.

MODX 2.6.1
Call to Action TV 1.0.0

**Comment by sdrenth** [comment]
This fix will be added in the next release.
