### ISSUE TITLE
Adding text with a ' to button text causes manager errors

### ISSUE THREAD

**Issue by gleighfield** [Sterc/calltoactiontv#4]
Adding text with a ' causes errors and prevents the UI from showing. Have to edit the content via the modx_site_tmplvar_contentvalues table to resolve.

![image](https://user-images.githubusercontent.com/1083436/46217088-edccb180-c338-11e8-818a-7bd598917d96.png)

**Comment by sdrenth** [comment]
@gleighfield This fix will be added in the next release.
