### ISSUE TITLE
Javascript error if type is not "resource"

### ISSUE THREAD

**Issue by kinaz** [Sterc/calltoactiontv#9]
Hi,

If type is not set to "resource" a javascript error is triggered when the resource page is loaded.

See attached screenshot:
![Schermata 2019-09-13 alle 10 52 22](https://user-images.githubusercontent.com/52575/64849901-ace6af00-d614-11e9-979e-e287edb54166.png)

**Comment by devlanda** [comment]
@kinaz Thank you for your contribution. I have merged your commits and released v1.0.4.
